# Use container-based distribution
sudo: false
dist: trusty
language: c++
addons:
  apt:
    sources: &default_sources
      - ubuntu-toolchain-r-test
matrix:
  include:
    - env: BUILD_SYSTEM=cmake _CXX=g++-6
      os: linux
      language: cpp
      addons:
        apt:
          sources:
            - *default_sources
          packages:
            - g++-6
    - env: BUILD_SYSTEM=meson _CXX=g++-6
      os: linux
      language: cpp
      python: 3.5
      addons:
        apt:
          sources:
            - *default_sources
          packages:
            - ninja-build
            - g++-6
      before_install:
        - pyenv global system 3.5
      install:
        - pip3 install meson
script:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.9/cmake-3.9.4-Linux-x86_64.tar.gz";
      mkdir cmake-bin && wget --quiet --no-check-certificate -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake-bin;
      export PATH=${PWD}/cmake-bin/bin:${PATH};
    fi
  - git submodule update --recursive --init
  - mkdir -p build/debug
  - cd build/debug
  - if [[ "${BUILD_SYSTEM}" == "cmake" ]]; then
      cmake ../.. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=$_CXX -DTOKENIZE_BUILD_TESTS=ON -DPDDL_BUILD_TESTS=ON -DPLASP_BUILD_TESTS=ON;
      make -j3 plasp-app && make -j3 run-tokenize-tests && make -j3 run-pddl-tests && make -j3 run-tests;
    elif [[ "${BUILD_SYSTEM}" == "meson" ]]; then
      CXX=${_CXX} meson ../.. --buildtype=debug;
      ninja plasp && ninja test;
    fi
